### ISSUE TITLE
I would like to add more hotkeys

### ISSUE THREAD

**Issue by ropelletier** [kopsap4ik/ScoreBoard#2]
**Is your feature request related to a problem? Please describe.**
I would like to add some hotkeys; could you point me in the right direction?

**Describe the solution you'd like**
I want to add hotkeys for +2 score, specifically for basketball games. I am happy to do the code myself, but I am unfamiliar with developing in xcode. Any help is very appreciated

**Comment by kopsap4ik** [comment]
It's easy, you don't even need to write any code.

1. Open the project in Xcode.
2. Select Main.storyboard file (ScoreBoard / Modules / MainViewController / Main.storyboard)
3. Go to the desired menu item (example in the picture).
4. In Attributes Inspector (column on the right) specify hotkeys for the selected menu item.

_In the next version of the program, hotkeys will be used, as indicated in the screenshot._

<img width="1792" alt="Hotkeys-ScroBoard-project" src="https://user-images.githubusercontent.com/61139898/139555970-7efaef0d-2c56-44bb-bf0a-ebe9c36667b2.png">

**Comment by kopsap4ik** [comment]
Version 1.1 has been released in the AppStore with hotkeys for all goals changing buttons.
