### ISSUE TITLE
Add penalties (number of players and penalty time)

### ISSUE THREAD

**Issue by alainmolimard** [kopsap4ik/ScoreBoard#3]
ScoreBoard is excellent. The only feature I feel is missing is to be able to add penalty countdowns.
 Maybe a list could be added below each team to allow entering the player's number getting the penalty was well as the amount (2 min, 4 min, 5, etc). 
Each penalty row would generate to files:

home_penalty_1_player_number.txt home_penalty_1_countdown.txt
visitor_penalty_1_player_number.txt visitor_penalty_1_countdown.txt

Keep up the good work.

Alain

**Comment by kopsap4ik** [comment]
The ice hockey penalty (player number and timer) will be added to the app. 
But for now I’m not wondering when it will be implemented, since this is not a very simple task and for now I’m thinking over a convenient and logical use case.

**Comment by kopsap4ik** [comment]
v1.3 released in Mac AppStore with penalties.
